### ISSUE TITLE
Mix of video and image urls in list

### ISSUE THREAD

**Issue by saintjab** [Zeuskartik/MediaSliderView#6]
Hey, great library. I am trying to run something like this
loadMediaSliderView(list,"video|image",true,true,false,"Image-Slider","#000000",null,0)

I have a list of urls for videos and images. How can I use the library to load all and then pick the appropriate image viewer or video player based on type

**Comment by Zeuskartik** [comment]
@saintjab Thanks for your support, but as of now you can only choose one...either image or video, so "image|video" won't work. If it is a mix of image and video URL's, it will only show the thumbnail of the video and won't actually load the video. I will try to implement the "mixed" thing in the future update because i feel it will be a great enhancement. Sorry :(

**Comment by baronha** [comment]
Does this library already have this feature?
